package com.example.bean;

import lombok.Data;

import java.util.Date;

@Data
public class Person {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_test_person.id
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_test_person.account
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_test_person.username
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_test_person.password
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_test_person.status
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_test_person.age
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_test_person.sex
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_test_person.telphone
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_test_person.email
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_test_person.create_time
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_test_person.update_time
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_test_person.id
     *
     * @return the value of tbl_test_person.id
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_test_person.id
     *
     * @param id the value for tbl_test_person.id
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_test_person.account
     *
     * @return the value of tbl_test_person.account
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_test_person.account
     *
     * @param account the value for tbl_test_person.account
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_test_person.username
     *
     * @return the value of tbl_test_person.username
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_test_person.username
     *
     * @param username the value for tbl_test_person.username
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_test_person.password
     *
     * @return the value of tbl_test_person.password
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_test_person.password
     *
     * @param password the value for tbl_test_person.password
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_test_person.status
     *
     * @return the value of tbl_test_person.status
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_test_person.status
     *
     * @param status the value for tbl_test_person.status
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_test_person.age
     *
     * @return the value of tbl_test_person.age
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_test_person.age
     *
     * @param age the value for tbl_test_person.age
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_test_person.sex
     *
     * @return the value of tbl_test_person.sex
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_test_person.sex
     *
     * @param sex the value for tbl_test_person.sex
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_test_person.telphone
     *
     * @return the value of tbl_test_person.telphone
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_test_person.telphone
     *
     * @param telphone the value for tbl_test_person.telphone
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_test_person.email
     *
     * @return the value of tbl_test_person.email
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_test_person.email
     *
     * @param email the value for tbl_test_person.email
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_test_person.create_time
     *
     * @return the value of tbl_test_person.create_time
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_test_person.create_time
     *
     * @param createTime the value for tbl_test_person.create_time
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_test_person.update_time
     *
     * @return the value of tbl_test_person.update_time
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_test_person.update_time
     *
     * @param updateTime the value for tbl_test_person.update_time
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}