spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/workspace
    username: root
    password: QQaaws1313
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.example.bean