package com.example.dao;

import com.example.bean.Person;
import com.example.bean.PersonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_test_person
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    int countByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_test_person
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    int deleteByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_test_person
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_test_person
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_test_person
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    int insertSelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_test_person
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    List<Person> selectByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_test_person
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    Person selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_test_person
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_test_person
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    int updateByExample(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_test_person
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    int updateByPrimaryKeySelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_test_person
     *
     * @mbggenerated Fri Jan 11 20:46:19 CST 2019
     */
    int updateByPrimaryKey(Person record);
}